// 성경구절 & 명언 & 사자성어 데이터
// type: "bible" | "quote" | "idiom"
// id: 상세 페이지(quotes/{id}.html) 연결용 고유 식별자
// tags: 감정/상황별 태그 (필터링용)
const CONTENT_DATA = [
  { id: "b1", type: "bible", text: "내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라.", source: "빌립보서 4:13", tags: ["지혜"] },
  { id: "b2", type: "bible", text: "여호와는 나의 목자시니 내게 부족함이 없으리로다.", source: "시편 23:1", tags: ["지혜"] },
  { id: "b3", type: "bible", text: "두려워하지 말라 내가 너와 함께 함이라 놀라지 말라 나는 네 하나님이 됨이라.", source: "이사야 41:10", tags: ["위로"] },
  { id: "b4", type: "bible", text: "범사에 감사하라 이것이 그리스도 예수 안에서 너희를 향하신 하나님의 뜻이니라.", source: "데살로니가전서 5:18", tags: ["감사"] },
  { id: "b5", type: "bible", text: "네 모든 것을 다하여 여호와를 신뢰하고 네 명철을 의지하지 말라.", source: "잠언 3:5", tags: ["지혜"] },
  { id: "b6", type: "bible", text: "구하라 그리하면 너희에게 주실 것이요 찾으라 그리하면 찾아낼 것이요.", source: "마태복음 7:7", tags: ["지혜"] },
  { id: "b7", type: "bible", text: "사랑은 오래 참고 사랑은 온유하며 시기하지 아니하며 자랑하지 아니하며.", source: "고린도전서 13:4", tags: ["사랑", "도전", "인내"] },
  { id: "b8", type: "bible", text: "내가 너희에게 평안을 끼치노니 곧 나의 평안을 너희에게 주노라.", source: "요한복음 14:27", tags: ["평안"] },
  { id: "b9", type: "bible", text: "새 일을 행하리니 이제 나타낼 것이라 너희가 그것을 알지 못하겠느냐.", source: "이사야 43:19", tags: ["아침"] },
  { id: "b10", type: "bible", text: "환난 날에 나를 부르라 내가 너를 건지리니 네가 나를 영화롭게 하리로다.", source: "시편 50:15", tags: ["지혜"] },
  { id: "b11", type: "bible", text: "쉬지 말고 기도하라.", source: "데살로니가전서 5:17", tags: ["지혜"] },
  { id: "b12", type: "bible", text: "마음의 소원대로 형통하게 하시기를 원하노라.", source: "시편 20:4", tags: ["지혜"] },
  { id: "b13", type: "bible", text: "그런즉 누구든지 그리스도 안에 있으면 새로운 피조물이라.", source: "고린도후서 5:17", tags: ["지혜"] },
  { id: "b14", type: "bible", text: "여호와를 기뻐하라 그가 네 마음의 소원을 이루어 주시리로다.", source: "시편 37:4", tags: ["성공"] },
  { id: "b15", type: "bible", text: "지금까지 지내온 것 에벤에셀이라 여호와께서 여기까지 도우셨다.", source: "사무엘상 7:12", tags: ["지혜"] },
  { id: "b16", type: "bible", text: "내가 산을 향하여 눈을 들리라 나의 도움이 어디서 올까.", source: "시편 121:1", tags: ["지혜"] },
  { id: "b17", type: "bible", text: "형제들아 내가 아직 내 자신이 잡은 줄로 여기지 아니하고 오직 한 일 앞에 있는 것을 잡으려고 달려가노라.", source: "빌립보서 3:13-14", tags: ["지혜"] },
  { id: "b18", type: "bible", text: "네가 어디로 가든지 네 하나님 여호와가 너와 함께 하느니라.", source: "여호수아 1:9", tags: ["지혜"] },
  { id: "b19", type: "bible", text: "너희 염려를 다 주께 맡기라 이는 그가 너희를 돌보심이라.", source: "베드로전서 5:7", tags: ["지혜"] },
  { id: "b20", type: "bible", text: "믿음은 바라는 것들의 실상이요 보이지 않는 것들의 증거니.", source: "히브리서 11:1", tags: ["지혜"] },
  { id: "b21", type: "bible", text: "선을 행하되 낙심하지 말지니 포기하지 아니하면 때가 이르매 거두리라.", source: "갈라디아서 6:9", tags: ["도전"] },
  { id: "b22", type: "bible", text: "여호와는 선하시며 환난 날에 산성이시라.", source: "나훔 1:7", tags: ["평안"] },
  { id: "b23", type: "bible", text: "너희 안에서 착한 일을 시작하신 이가 그리스도 예수의 날까지 이루실 줄을 확신하노라.", source: "빌립보서 1:6", tags: ["도전", "성공"] },
  { id: "b24", type: "bible", text: "강하고 담대하라 두려워하지 말며 놀라지 말라.", source: "여호수아 1:9", tags: ["위로", "도전"] },
  { id: "b25", type: "bible", text: "겸손한 자에게는 은혜를 베푸시느니라.", source: "야고보서 4:6", tags: ["지혜"] },
  { id: "b26", type: "bible", text: "하나님이 세상을 이처럼 사랑하사 독생자를 주셨으니.", source: "요한복음 3:16", tags: ["사랑"] },
  { id: "b27", type: "bible", text: "항상 기뻐하라.", source: "데살로니가전서 5:16", tags: ["지혜"] },
  { id: "b28", type: "bible", text: "내가 새 영을 너희 속에 두고 새 마음을 너희에게 주되.", source: "에스겔 36:26", tags: ["아침"] },
  { id: "b29", type: "bible", text: "여호와를 앙망하는 자는 새 힘을 얻으리니 독수리가 날개치며 올라감 같을 것이요.", source: "이사야 40:31", tags: ["아침"] },
  { id: "b30", type: "bible", text: "지혜가 부족하거든 하나님께 구하라 그리하면 주시리라.", source: "야고보서 1:5", tags: ["지혜"] },
  { id: "b31", type: "bible", text: "낙심하지 말라 내가 너의 하나님이 됨이니라.", source: "이사야 41:10", tags: ["지혜"] },
  { id: "b32", type: "bible", text: "선한 싸움을 싸우고 나의 달려갈 길을 마치고 믿음을 지켰으니.", source: "디모데후서 4:7", tags: ["지혜"] },
  { id: "b33", type: "bible", text: "사람이 마음으로 자기의 길을 계획할지라도 그의 걸음을 인도하시는 이는 여호와시니라.", source: "잠언 16:9", tags: ["지혜"] },
  { id: "b34", type: "bible", text: "우리가 알거니와 하나님을 사랑하는 자 곧 그의 뜻대로 부르심을 입은 자들에게는 모든 것이 합력하여 선을 이루느니라.", source: "로마서 8:28", tags: ["사랑", "성공"] },
  { id: "b35", type: "bible", text: "네 짐을 여호와께 맡기라 그가 너를 붙드시고 결코 의인의 요동함을 허락하지 아니하시리로다.", source: "시편 55:22", tags: ["지혜"] },
  { id: "b36", type: "bible", text: "그가 네 우편에 서사 너를 심판하는 자의 손에서 네 영혼을 건지시리로다.", source: "시편 109:31", tags: ["지혜"] },
  { id: "b37", type: "bible", text: "여호와의 인자하심으로 인하여 우리가 진멸되지 아니함이니 그 긍휼이 무궁하시므로.", source: "예레미야애가 3:22", tags: ["지혜"] },
  { id: "b38", type: "bible", text: "아무 것도 염려하지 말고 오직 모든 일에 기도와 간구로 너희 구할 것을 감사함으로 하나님께 아뢰라.", source: "빌립보서 4:6", tags: ["감사"] },
  { id: "b39", type: "bible", text: "평강의 하나님이 친히 너희를 온전히 거룩하게 하시고.", source: "데살로니가전서 5:23", tags: ["지혜"] },
  { id: "b40", type: "bible", text: "빛은 의인을 위하여 뿌려졌고 기쁨은 마음이 정직한 자를 위하여 뿌려졌도다.", source: "시편 97:11", tags: ["지혜"] },
  { id: "b41", type: "bible", text: "너희는 세상의 빛이라.", source: "마태복음 5:14", tags: ["지혜"] },
  { id: "b42", type: "bible", text: "오직 성령의 열매는 사랑과 희락과 화평과 오래 참음과 자비와 양선과 충성과.", source: "갈라디아서 5:22", tags: ["사랑"] },
  { id: "b43", type: "bible", text: "내 은혜가 네게 족하도다 이는 내 능력이 약한 데서 온전하여짐이라.", source: "고린도후서 12:9", tags: ["지혜"] },
  { id: "b44", type: "bible", text: "우리가 섬기는 하나님이 우리를 능히 건져내시겠고 왕의 손에서도 건져내시리이다.", source: "다니엘 3:17", tags: ["지혜"] },
  { id: "b45", type: "bible", text: "하나님은 우리의 피난처시요 힘이시니 환난 중에 만날 큰 도움이시라.", source: "시편 46:1", tags: ["평안"] },
  { id: "b46", type: "bible", text: "모든 지킬 만한 것 중에 더욱 네 마음을 지키라 생명의 근원이 이에서 남이니라.", source: "잠언 4:23", tags: ["지혜"] },
  { id: "b47", type: "bible", text: "여호와는 마음이 상한 자를 가까이 하시고 충심으로 통회하는 자를 구원하시는도다.", source: "시편 34:18", tags: ["위로"] },
  { id: "b48", type: "bible", text: "너희는 먼저 그의 나라와 그의 의를 구하라 그리하면 이 모든 것을 너희에게 더하시리라.", source: "마태복음 6:33", tags: ["지혜"] },
  { id: "b49", type: "bible", text: "여호와의 이름은 견고한 망대라 의인은 그리로 달려가서 안전함을 얻느니라.", source: "잠언 18:10", tags: ["평안"] },
  { id: "b50", type: "bible", text: "여호와는 나의 빛이요 나의 구원이시니 내가 누구를 두려워하리요.", source: "시편 27:1", tags: ["지혜"] },
  { id: "b51", type: "bible", text: "너희는 이 세대를 본받지 말고 오직 마음을 새롭게 함으로 변화를 받아라.", source: "로마서 12:2", tags: ["아침"] },
  { id: "b52", type: "bible", text: "하나님은 미쁘사 너희가 감당하지 못할 시험 당함을 허락하지 아니하시고 시험 당할 즈음에 피할 길을 내시느니라.", source: "고린도전서 10:13", tags: ["도전"] },
  { id: "b53", type: "bible", text: "이 날은 여호와께서 정하신 것이라 이 날에 우리가 즐거워하고 기뻐하리로다.", source: "시편 118:24", tags: ["지혜"] },
  { id: "b54", type: "bible", text: "수고하고 무거운 짐 진 자들아 다 내게로 오라 내가 너희를 쉬게 하리라.", source: "마태복음 11:28", tags: ["평안"] },
  { id: "b55", type: "bible", text: "마음의 즐거움은 양약이라도 심령의 근심은 뼈로 마르게 하느니라.", source: "잠언 17:22", tags: ["위로"] },
  { id: "b56", type: "bible", text: "아침에 나로 주의 인자한 말씀을 듣게 하소서 내가 주를 의뢰함이니이다.", source: "시편 143:8", tags: ["아침"] },
  { id: "b57", type: "bible", text: "진리를 알지니 진리가 너희를 자유롭게 하리라.", source: "요한복음 8:32", tags: ["지혜"] },
  { id: "b58", type: "bible", text: "우리는 그가 만드신 바라 그리스도 예수 안에서 선한 일을 위하여 지으심을 받은 자니.", source: "에베소서 2:10", tags: ["지혜"] },
  { id: "b59", type: "bible", text: "대저 의인은 일곱 번 넘어질지라도 다시 일어나려니와.", source: "잠언 24:16", tags: ["도전"] },
  { id: "b60", type: "bible", text: "저녁에는 울음이 깃들일지라도 아침에는 기쁨이 오리로다.", source: "시편 30:5", tags: ["아침"] },
  { id: "b61", type: "bible", text: "그러므로 피차 권면하고 서로 덕을 세우기를 하던 대로 하라.", source: "데살로니가전서 5:11", tags: ["관계"] },
  { id: "b62", type: "bible", text: "사랑 안에 두려움이 없고 온전한 사랑이 두려움을 내쫓나니.", source: "요한일서 4:18", tags: ["사랑"] },
  { id: "b63", type: "bible", text: "여호와를 경외하는 것이 지식의 근본이거늘.", source: "잠언 1:7", tags: ["지혜"] },
  { id: "b64", type: "bible", text: "우리에게 우리 날 계수함을 가르치사 지혜로운 마음을 얻게 하소서.", source: "시편 90:12", tags: ["지혜"] },
  { id: "b65", type: "bible", text: "너희 빛을 사람 앞에 비치게 하여 그들로 너희 착한 행실을 보고 하늘에 계신 너희 아버지께 영광을 돌리게 하라.", source: "마태복음 5:16", tags: ["지혜"] },
  { id: "b66", type: "bible", text: "우리가 낙심하지 아니하노니 겉사람은 낡아지나 우리의 속사람은 날로 새로워지도다.", source: "고린도후서 4:16", tags: ["지혜"] },
  { id: "b67", type: "bible", text: "모든 무거운 것과 얽매이기 쉬운 죄를 벗어 버리고 인내로써 우리 앞에 당한 경주를 하며.", source: "히브리서 12:1", tags: ["인내"] },
  { id: "b68", type: "bible", text: "주께서 생명의 길을 내게 보이시리니 주의 앞에는 충만한 기쁨이 있고 주의 오른쪽에는 영원한 즐거움이 있나이다.", source: "시편 16:11", tags: ["지혜"] },

  { id: "q1", type: "quote", text: "성공은 최종적인 것이 아니고 실패는 치명적인 것이 아니다. 중요한 것은 계속하는 용기다.", source: "윈스턴 처칠", tags: ["도전", "성공"] },
  { id: "q2", type: "quote", text: "우리가 가진 유일한 한계는 우리 스스로가 만드는 것이다.", source: "레스 브라운", tags: ["도전"] },
  { id: "q3", type: "quote", text: "행복은 습관이다. 그것을 몸에 지니라.", source: "허버드", tags: ["도전"] },
  { id: "q4", type: "quote", text: "천 리 길도 한 걸음부터.", source: "노자", tags: ["도전"] },
  { id: "q5", type: "quote", text: "네가 할 수 있다고 믿든 할 수 없다고 믿든, 네 말이 맞다.", source: "헨리 포드", tags: ["도전"] },
  { id: "q6", type: "quote", text: "오늘 할 수 있는 일에 전력을 다하라. 그러면 내일은 한 걸음 더 진보한다.", source: "아이작 뉴턴", tags: ["도전"] },
  { id: "q7", type: "quote", text: "삶이 있는 한 희망은 있다.", source: "키케로", tags: ["도전"] },
  { id: "q8", type: "quote", text: "가장 큰 영광은 한 번도 실패하지 않는 것이 아니라 실패할 때마다 다시 일어서는 데 있다.", source: "공자", tags: ["도전"] },
  { id: "q9", type: "quote", text: "당신이 무엇을 할 수 있다고 꿈꾸든, 그것을 시작하라. 대담함은 그 안에 천재성과 힘과 마법을 지니고 있다.", source: "괴테", tags: ["도전"] },
  { id: "q10", type: "quote", text: "나는 실패한 적이 없다. 단지 작동하지 않는 만 가지 방법을 발견했을 뿐이다.", source: "토마스 에디슨", tags: ["도전"] },
  { id: "q11", type: "quote", text: "인생에서 가장 큰 영광은 결코 넘어지지 않는 데 있는 것이 아니라 넘어질 때마다 다시 일어서는 데 있다.", source: "넬슨 만델라", tags: ["도전"] },
  { id: "q12", type: "quote", text: "다른 사람의 삶을 사느라 시간을 낭비하지 마라.", source: "스티브 잡스", tags: ["도전"] },
  { id: "q13", type: "quote", text: "배움에는 끝이 없다. 죽는 날까지 배워야 한다.", source: "공자", tags: ["도전"] },
  { id: "q14", type: "quote", text: "행복한 삶을 위해 필요한 것은 거의 없다. 모든 것은 당신 자신, 당신의 생각 방식에 달려 있다.", source: "마르쿠스 아우렐리우스", tags: ["도전"] },
  { id: "q15", type: "quote", text: "오늘 걷지 않으면 내일은 뛰어야 한다.", source: "에이브러햄 링컨", tags: ["도전"] },
  { id: "q16", type: "quote", text: "가장 어두운 밤도 언젠가는 끝나고 태양은 다시 떠오른다.", source: "빅토르 위고", tags: ["도전"] },
  { id: "q17", type: "quote", text: "시작이 반이다.", source: "아리스토텔레스", tags: ["도전"] },
  { id: "q18", type: "quote", text: "위대한 일을 하는 유일한 방법은 자신이 하는 일을 사랑하는 것이다.", source: "스티브 잡스", tags: ["사랑"] },
  { id: "q19", type: "quote", text: "삶은 자전거를 타는 것과 같다. 균형을 잡으려면 계속 움직여야 한다.", source: "알버트 아인슈타인", tags: ["도전"] },
  { id: "q20", type: "quote", text: "지식은 힘이다.", source: "프랜시스 베이컨", tags: ["지혜"] },
  { id: "q21", type: "quote", text: "인간의 모든 지혜는 기다림과 희망 두 단어로 요약될 수 있다.", source: "알렉상드르 뒤마", tags: ["지혜"] },
  { id: "q22", type: "quote", text: "세상을 바꾸고 싶다면 먼저 자신부터 변화시켜라.", source: "마하트마 간디", tags: ["도전"] },
  { id: "q23", type: "quote", text: "고난이 남기고 간 뒤를 보라. 고난이 지나면 반드시 기쁨이 스며든다.", source: "괴테", tags: ["도전"] },
  { id: "q24", type: "quote", text: "장애물은 목표를 향해 시선을 떼지 않을 때 사라진다.", source: "헨리 포드", tags: ["도전"] },
  { id: "q25", type: "quote", text: "겨울이 오면 봄이 멀지 않으리.", source: "퍼시 셸리", tags: ["도전"] },
  { id: "q26", type: "quote", text: "할 수 있다고 믿는 사람은 그렇게 되고, 할 수 없다고 믿는 사람도 역시 그렇게 된다.", source: "샤를 드골", tags: ["도전"] },
  { id: "q27", type: "quote", text: "포기하지 않는 한 실패한 것이 아니다.", source: "마이클 조던", tags: ["도전"] },
  { id: "q28", type: "quote", text: "성실은 성공의 어머니다.", source: "벤자민 디즈레일리", tags: ["성공"] },
  { id: "q29", type: "quote", text: "타인을 알면 지혜롭고 자신을 알면 밝다.", source: "노자", tags: ["지혜"] },
  { id: "q30", type: "quote", text: "삶의 목적은 행복해지는 것이 아니라 쓸모 있고, 존경받고, 자비로운 사람이 되는 것이다.", source: "랄프 왈도 에머슨", tags: ["도전"] },
  { id: "q31", type: "quote", text: "위기는 곧 기회다.", source: "존 F. 케네디", tags: ["도전"] },
  { id: "q32", type: "quote", text: "말보다 행동이 더 크게 말한다.", source: "마크 트웨인", tags: ["도전"] },
  { id: "q33", type: "quote", text: "자신을 믿어라. 그러면 무엇을 해야 할지 알게 될 것이다.", source: "요한 볼프강 폰 괴테", tags: ["도전"] },
  { id: "q34", type: "quote", text: "행운은 준비가 기회를 만났을 때 생긴다.", source: "세네카", tags: ["도전"] },
  { id: "q35", type: "quote", text: "오늘이라는 날은 두 번 다시 오지 않는다.", source: "단테", tags: ["도전"] },
  { id: "q36", type: "quote", text: "눈물과 함께 빵을 먹어보지 않은 사람은 인생의 참맛을 모른다.", source: "괴테", tags: ["위로"] },
  { id: "q37", type: "quote", text: "당신 자신이 세상에서 보고 싶은 변화가 되어라.", source: "마하트마 간디", tags: ["도전"] },
  { id: "q38", type: "quote", text: "완벽함은 더 이상 더할 것이 없을 때가 아니라 더 이상 뺄 것이 없을 때 완성된다.", source: "생텍쥐페리", tags: ["도전"] },
  { id: "q39", type: "quote", text: "삶에서 실패한 사람 중 다수는 성공을 눈앞에 두고도 모른 채 포기한 사람들이다.", source: "토마스 에디슨", tags: ["성공"] },
  { id: "q40", type: "quote", text: "고통 없이는 얻는 것도 없다.", source: "벤자민 프랭클린", tags: ["도전"] },
  { id: "q41", type: "quote", text: "당신의 시간은 한정되어 있다. 다른 사람의 삶을 사느라 그것을 낭비하지 마라.", source: "스티브 잡스", tags: ["도전"] },
  { id: "q42", type: "quote", text: "훌륭한 배는 항구에 있을 때 가장 안전하다. 그러나 그것은 배가 만들어진 목적이 아니다.", source: "존 A. 셰드", tags: ["도전"] },
  { id: "q43", type: "quote", text: "친절한 말 한마디는 짧고 하기 쉽지만 그 울림은 참으로 끝이 없다.", source: "마더 테레사", tags: ["도전"] },
  { id: "q44", type: "quote", text: "인생은 우리가 매일 만드는 것이다.", source: "엘리너 루스벨트", tags: ["도전"] },
  { id: "q45", type: "quote", text: "가장 확실한 성공의 척도는 실패해도 열정을 잃지 않는 능력이다.", source: "윈스턴 처칠", tags: ["성공"] },
  { id: "q46", type: "quote", text: "웃음은 두 사람 사이의 가장 가까운 거리다.", source: "빅터 보르게", tags: ["도전"] },
  { id: "q47", type: "quote", text: "습관은 처음엔 거미줄처럼 약하지만 나중엔 쇠사슬처럼 강해진다.", source: "스페인 속담", tags: ["도전"] },
  { id: "q48", type: "quote", text: "실패는 성공의 어머니다.", source: "한국 속담", tags: ["성공"] },
  { id: "q49", type: "quote", text: "천재는 1퍼센트의 영감과 99퍼센트의 노력으로 이루어진다.", source: "토마스 에디슨", tags: ["성공"] },
  { id: "q50", type: "quote", text: "네 자신을 아는 것이 모든 지혜의 시작이다.", source: "소크라테스", tags: ["도전", "지혜"] },
  { id: "q51", type: "quote", text: "인내는 쓰지만 그 열매는 달다.", source: "장 자크 루소", tags: ["인내"] },
  { id: "q52", type: "quote", text: "가장 큰 위험은 위험 없는 삶을 사는 것이다.", source: "쇠렌 키르케고르", tags: ["도전"] },
  { id: "q53", type: "quote", text: "자기 자신을 이기는 것이 가장 위대한 승리다.", source: "플라톤", tags: ["도전"] },
  { id: "q54", type: "quote", text: "생각이 바뀌면 행동이 바뀌고, 행동이 바뀌면 습관이 바뀌고, 습관이 바뀌면 인격이 바뀐다.", source: "윌리엄 제임스", tags: ["도전"] },
  { id: "q55", type: "quote", text: "위대한 일은 힘이 아니라 인내로 이루어진다.", source: "새뮤얼 존슨", tags: ["성공", "인내"] },
  { id: "q56", type: "quote", text: "재능은 노력이라는 거름을 먹고 자란다.", source: "안톤 체호프", tags: ["도전"] },
  { id: "q57", type: "quote", text: "오늘 하는 일에 정성을 다하면 내일은 저절로 좋아진다.", source: "공자", tags: ["도전"] },
  { id: "q58", type: "quote", text: "행동이 반드시 행복을 주는 것은 아니지만 행동 없는 행복은 없다.", source: "윌리엄 제임스", tags: ["도전"] },
  { id: "q59", type: "quote", text: "가장 유능한 사람은 가장 배우기를 열망하는 사람이다.", source: "요한 볼프강 폰 괴테", tags: ["도전"] },
  { id: "q60", type: "quote", text: "고요한 물이 깊이 흐른다.", source: "서양 속담", tags: ["도전"] },
  { id: "q61", type: "quote", text: "돌을 뒤집어 보지 않으면 그 밑에 무엇이 있는지 알 수 없다.", source: "에우리피데스", tags: ["도전"] },
  { id: "q62", type: "quote", text: "말은 마음의 초상이다.", source: "세네카", tags: ["도전"] },
  { id: "q63", type: "quote", text: "노력은 결코 배신하지 않는다.", source: "한국 속담", tags: ["도전"] },
  { id: "q64", type: "quote", text: "겨울이 지나야 봄의 소중함을 안다.", source: "한국 속담", tags: ["도전"] },
  { id: "q65", type: "quote", text: "가장 높은 곳에 오르려면 가장 낮은 곳에서 시작해야 한다.", source: "이솝", tags: ["도전"] },
  { id: "q66", type: "quote", text: "오늘의 준비가 내일의 성공을 만든다.", source: "격언", tags: ["성공"] },
  { id: "q67", type: "quote", text: "구르는 돌에는 이끼가 끼지 않는다.", source: "서양 속담", tags: ["도전"] },
  { id: "q68", type: "quote", text: "하늘은 스스로 돕는 자를 돕는다.", source: "새뮤얼 스마일스", tags: ["도전"] },
  { id: "q69", type: "quote", text: "시작을 알리는 첫걸음은 언제나 가장 용기 있는 걸음이다.", source: "격언", tags: ["도전"] },
  { id: "q70", type: "quote", text: "배운 자는 늙지 않는다.", source: "격언", tags: ["도전"] },
  { id: "q71", type: "quote", text: "감사하는 마음은 모든 미덕의 어버이다.", source: "키케로", tags: ["감사"] },
  { id: "q72", type: "quote", text: "지금 가진 것에 감사할 줄 모르면 더 많이 가져도 만족하지 못한다.", source: "격언", tags: ["감사"] },
  { id: "q73", type: "quote", text: "일찍 일어나는 새가 먹이를 먼저 잡는다.", source: "서양 속담", tags: ["아침"] },
  { id: "q74", type: "quote", text: "오늘 아침을 웃음으로 시작하면 하루가 달라진다.", source: "격언", tags: ["아침"] },
  { id: "q75", type: "quote", text: "혼자 가면 빨리 가고 함께 가면 멀리 간다.", source: "아프리카 속담", tags: ["관계"] },
  { id: "q76", type: "quote", text: "좋은 친구 한 명은 천 명의 친척보다 낫다.", source: "유대 속담", tags: ["관계"] },
  { id: "q77", type: "quote", text: "고요한 마음이 가장 큰 재산이다.", source: "격언", tags: ["평안"] },
  { id: "q78", type: "quote", text: "평화는 밖에서 오지 않고 내 마음에서 시작된다.", source: "격언", tags: ["평안"] },

  { id: "i1", type: "idiom", text: "우공이산 (愚公移山)", source: "어리석어 보여도 꾸준히 노력하면 결국 큰 일을 이룰 수 있다", tags: ["인내"] },
  { id: "i2", type: "idiom", text: "마부작침 (磨斧作針)", source: "도끼를 갈아 바늘을 만들듯, 끈기 있게 노력하면 무엇이든 이룰 수 있다", tags: ["도전", "인내"] },
  { id: "i3", type: "idiom", text: "수적천석 (水滴穿石)", source: "작은 물방울이 바위를 뚫듯, 작은 노력도 꾸준히 쌓이면 큰 결과를 만든다", tags: ["인내"] },
  { id: "i4", type: "idiom", text: "절차탁마 (切磋琢磨)", source: "옥돌을 갈고 닦듯 학문과 인격을 끊임없이 갈고닦음", tags: ["인내"] },
  { id: "i5", type: "idiom", text: "형설지공 (螢雪之功)", source: "어려운 환경에서도 꾸준히 노력해 이룬 성과", tags: ["인내"] },
  { id: "i6", type: "idiom", text: "대기만성 (大器晩成)", source: "큰 그릇은 늦게 이루어지듯, 크게 될 사람은 늦더라도 결국 성공한다", tags: ["성공"] },
  { id: "i7", type: "idiom", text: "일신우일신 (日新又日新)", source: "날마다 새롭게 하고 또 날마다 새롭게 함", tags: ["아침"] },
  { id: "i8", type: "idiom", text: "자강불식 (自强不息)", source: "스스로 강해지기 위해 끊임없이 노력함", tags: ["인내"] },
  { id: "i9", type: "idiom", text: "우보만리 (牛步萬里)", source: "소걸음처럼 느리더라도 꾸준히 나아가면 큰 성취를 이룬다", tags: ["성공", "인내"] },
  { id: "i10", type: "idiom", text: "진인사대천명 (盡人事待天命)", source: "할 수 있는 일을 다 하고 나서 결과는 하늘의 뜻에 맡김", tags: ["인내"] },
  { id: "i11", type: "idiom", text: "칠전팔기 (七顚八起)", source: "일곱 번 넘어져도 여덟 번 일어나듯, 실패해도 포기하지 않음", tags: ["도전"] },
  { id: "i12", type: "idiom", text: "백절불굴 (百折不屈)", source: "백 번 꺾여도 굴하지 않는 강한 의지", tags: ["인내"] },
  { id: "i13", type: "idiom", text: "초지일관 (初志一貫)", source: "처음에 세운 뜻을 끝까지 밀고 나감", tags: ["인내"] },
  { id: "i14", type: "idiom", text: "불철주야 (不撤晝夜)", source: "밤낮을 가리지 않고 힘써 노력함", tags: ["인내"] },
  { id: "i15", type: "idiom", text: "각고면려 (刻苦勉勵)", source: "몸과 마음을 다해 어려움을 참고 힘써 노력함", tags: ["인내"] },
  { id: "i16", type: "idiom", text: "발분망식 (發憤忘食)", source: "끼니마저 잊을 정도로 무언가에 열중하여 노력함", tags: ["인내"] },
  { id: "i17", type: "idiom", text: "등고자비 (登高自卑)", source: "높은 곳에 오르려면 낮은 곳에서부터 시작해야 한다", tags: ["도전"] },
  { id: "i18", type: "idiom", text: "온고지신 (溫故知新)", source: "옛것을 익혀 그것을 바탕으로 새것을 앎", tags: ["인내"] },
  { id: "i19", type: "idiom", text: "교학상장 (敎學相長)", source: "가르치고 배우면서 서로 성장함", tags: ["관계"] },
  { id: "i20", type: "idiom", text: "개과천선 (改過遷善)", source: "지난 잘못을 고쳐 올바르고 착하게 됨", tags: ["인내"] },
  { id: "i21", type: "idiom", text: "새옹지마 (塞翁之馬)", source: "인생의 길흉화복은 알 수 없으니 지금의 불행에 낙담하지 말라", tags: ["인내"] },
  { id: "i22", type: "idiom", text: "전화위복 (轉禍爲福)", source: "화가 바뀌어 오히려 복이 됨", tags: ["인내"] },
  { id: "i23", type: "idiom", text: "고진감래 (苦盡甘來)", source: "쓴 것이 다하면 단 것이 오듯, 고생 끝에 낙이 온다", tags: ["인내"] },
  { id: "i24", type: "idiom", text: "유비무환 (有備無患)", source: "미리 준비되어 있으면 근심할 일이 없다", tags: ["위로"] },
  { id: "i25", type: "idiom", text: "심기일전 (心機一轉)", source: "어떤 계기로 마음가짐을 완전히 새롭게 바꿈", tags: ["아침"] },
  { id: "i26", type: "idiom", text: "사필귀정 (事必歸正)", source: "모든 일은 반드시 바른 이치대로 돌아간다", tags: ["인내"] },
  { id: "i27", type: "idiom", text: "지성감천 (至誠感天)", source: "지극한 정성은 하늘도 감동시킨다", tags: ["인내"] },
  { id: "i28", type: "idiom", text: "일취월장 (日就月將)", source: "나날이 다달이 발전하고 진보함", tags: ["인내"] },
  { id: "i29", type: "idiom", text: "견인불발 (堅忍不拔)", source: "굳게 참고 견디어 마음이 흔들리지 않음", tags: ["인내"] },
  { id: "i30", type: "idiom", text: "유지경성 (有志竟成)", source: "뜻이 있는 사람은 결국 그 뜻을 이룬다", tags: ["인내"] },
  { id: "i31", type: "idiom", text: "파부침주 (破釜沈舟)", source: "결연한 각오로 물러설 곳 없이 온 힘을 다해 임함", tags: ["인내"] },
  { id: "i32", type: "idiom", text: "근면성실 (勤勉誠實)", source: "부지런하고 정성스럽게 최선을 다함", tags: ["인내"] },
  { id: "i33", type: "idiom", text: "자수성가 (自手成家)", source: "스스로의 힘으로 어려움을 극복하고 성공을 이룸", tags: ["성공"] },
  { id: "i34", type: "idiom", text: "백문불여일견 (百聞不如一見)", source: "백 번 듣는 것이 한 번 보고 경험하는 것만 못하다", tags: ["인내"] },
  { id: "i35", type: "idiom", text: "청출어람 (靑出於藍)", source: "제자가 스승보다 뛰어나게 성장함", tags: ["성공", "관계"] },
  { id: "i36", type: "idiom", text: "불요불굴 (不撓不屈)", source: "뜻이 흔들리지 않고 어떤 어려움에도 굽히지 않음", tags: ["인내"] },
  { id: "i37", type: "idiom", text: "십년마검 (十年磨劍)", source: "오랜 시간 묵묵히 준비하고 노력함", tags: ["인내"] },
  { id: "i38", type: "idiom", text: "각골명심 (刻骨銘心)", source: "뼈에 새기듯 마음속 깊이 새겨 잊지 않음", tags: ["인내"] },
  { id: "i39", type: "idiom", text: "절치부심 (切齒腐心)", source: "실패를 딛고 이를 갈며 재도약을 다짐함", tags: ["인내"] },
  { id: "i40", type: "idiom", text: "와신상담 (臥薪嘗膽)", source: "목표를 이루기 위해 온갖 고난을 참고 견딤", tags: ["성공", "인내"] },
  { id: "i41", type: "idiom", text: "금실지락 (琴瑟之樂)", source: "부부 사이의 화목하고 다정한 사랑을 이르는 말", tags: ["사랑"] },
  { id: "i42", type: "idiom", text: "애지중지 (愛之重之)", source: "몹시 사랑하고 소중히 여김", tags: ["사랑"] },
  { id: "i43", type: "idiom", text: "명경지수 (明鏡止水)", source: "맑은 거울과 고요한 물처럼 사심 없이 맑고 평온한 마음", tags: ["지혜", "평안"] },
  { id: "i44", type: "idiom", text: "심사숙고 (深思熟考)", source: "깊이 생각하고 신중하게 고민함", tags: ["지혜"] },
  { id: "i45", type: "idiom", text: "결초보은 (結草報恩)", source: "죽어서도 은혜를 잊지 않고 반드시 갚음", tags: ["감사"] },
  { id: "i46", type: "idiom", text: "각골난망 (刻骨難忘)", source: "입은 은혜를 뼈에 새기듯 결코 잊지 않음", tags: ["감사"] },
  { id: "i47", type: "idiom", text: "안분지족 (安分知足)", source: "편안한 마음으로 제 분수를 지키며 만족할 줄 앎", tags: ["평안"] }
];
